[package]
name = "pedal_pal"
version = "0.1.0"
edition = "2021"

[lib]
name = "pedal_pal"
path = "src/lib.rs"

[dependencies]
diesel = { version = "2.1.4", features = ["postgres", "r2d2"] }
uuid = { version = "1.3.0", features = ["v4"] }

[dev-dependencies]
diesel_migrations = "2.1.4"